name: spotfit
description: Streaming de música para treino — playlists de cardio, força e HIIT.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  just_audio: ^0.10.4
  audio_session: ^0.1.25
  provider: ^6.1.5
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
